### ISSUE TITLE
Wrong MailChimp url

### ISSUE THREAD

**Issue by makerovski** [Baroshem/nuxt-newsletter#29]
Hello Guys, I'd like to suggest a change in your plugin. I had a 500 error with MailChimp which was solved changing the line 2 in useNewsletterSubscribe.mjs.

```
export async function useNewsletterSubscribe(email) {
  return await $fetch("/api/newsletter/subscribe", {
    body: { email },
    method: "POST"
  }).catch((e) => e.data);
}

```
to:

```
export async function useNewsletterSubscribe(email) {
  return await $fetch("/api/newsletter/subscribe/members", {
    body: { email },
    method: "POST"
  }).catch((e) => e.data);
}
```

added `/members `

Thank you

**Comment by Baroshem** [comment]
Hey,

Thanks for raising this issue but don't think that's the correct approach here.
The path `/api/newsletter/subscribe` is just a path to a localhost endpoint for your server middleware to send the request to an appriopriate service (in this case mailchimp).

**Comment by makerovski** [comment]
Hello ... Thank you for your answer. Now I got it.
